"""update backtest

Revision ID: 11a76419fd12
Revises: ace3c9707e02
Create Date: 2024-11-27 18:41:17.728481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '11a76419fd12'
down_revision: Union[str, None] = 'ace3c9707e02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest', sa.Column('name', sa.String(), nullable=True))
    op.add_column('backtest', sa.Column('config', sa.JSON(), nullable=True))
    op.add_column('backtest', sa.Column('metric', sa.JSON(), nullable=True))
    op.drop_index('ix_backtest_symbol', table_name='backtest')
    op.drop_column('backtest', 'sharpe_ratio')
    op.drop_column('backtest', 'end')
    op.drop_column('backtest', 'start')
    op.drop_column('backtest', 'slippage')
    op.drop_column('backtest', 'cagr')
    op.drop_column('backtest', 'data_source')
    op.drop_column('backtest', 'strategies')
    op.drop_column('backtest', 'symbol')
    op.drop_column('backtest', 'fees')
    op.drop_column('backtest', 'max_drawdown')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest', sa.Column('max_drawdown', sa.INTEGER(), nullable=True))
    op.add_column('backtest', sa.Column('fees', sa.INTEGER(), nullable=True))
    op.add_column('backtest', sa.Column('symbol', sa.VARCHAR(), nullable=True))
    op.add_column('backtest', sa.Column('strategies', sqlite.JSON(), nullable=True))
    op.add_column('backtest', sa.Column('data_source', sa.VARCHAR(), nullable=True))
    op.add_column('backtest', sa.Column('cagr', sa.INTEGER(), nullable=True))
    op.add_column('backtest', sa.Column('slippage', sa.INTEGER(), nullable=True))
    op.add_column('backtest', sa.Column('start', sa.VARCHAR(), nullable=True))
    op.add_column('backtest', sa.Column('end', sa.VARCHAR(), nullable=True))
    op.add_column('backtest', sa.Column('sharpe_ratio', sa.INTEGER(), nullable=True))
    op.create_index('ix_backtest_symbol', 'backtest', ['symbol'], unique=False)
    op.drop_column('backtest', 'metric')
    op.drop_column('backtest', 'config')
    op.drop_column('backtest', 'name')
    # ### end Alembic commands ###
