"""email in backtest

Revision ID: 3b26b0303bda
Revises: 3b6277bb7352
Create Date: 2024-10-31 15:47:05.673157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '3b26b0303bda'
down_revision: Union[str, None] = '3b6277bb7352'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_backtest_email', table_name='backtest')
    op.create_index(op.f('ix_backtest_email'), 'backtest', ['email'], unique=False)
    op.drop_column('backtest', 'results')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest', sa.Column('results', sqlite.JSON(), nullable=True))
    op.drop_index(op.f('ix_backtest_email'), table_name='backtest')
    op.create_index('ix_backtest_email', 'backtest', ['email'], unique=1)
    # ### end Alembic commands ###
