"""Backtest & Strategy

Revision ID: 3b6277bb7352
Revises: 4ed8296af2cb
Create Date: 2024-10-24 13:58:47.495368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b6277bb7352'
down_revision: Union[str, None] = '4ed8296af2cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('start', sa.String(), nullable=True),
    sa.Column('end', sa.String(), nullable=True),
    sa.Column('fees', sa.Integer(), nullable=True),
    sa.Column('slippage', sa.Integer(), nullable=True),
    sa.Column('strategies', sa.JSON(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_email'), 'backtest', ['email'], unique=True)
    op.create_index(op.f('ix_backtest_id'), 'backtest', ['id'], unique=False)
    op.create_index(op.f('ix_backtest_symbol'), 'backtest', ['symbol'], unique=False)
    op.create_table('strategy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('allocation', sa.Integer(), nullable=True),
    sa.Column('positionType', sa.String(), nullable=True),
    sa.Column('entryRules', sa.JSON(), nullable=True),
    sa.Column('exitRules', sa.JSON(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('regime_filter', sa.String(), nullable=True),
    sa.Column('position_size_method', sa.String(), nullable=True),
    sa.Column('fixed_position_size', sa.Float(), nullable=True),
    sa.Column('volatility_target', sa.Float(), nullable=True),
    sa.Column('volatility_lookback', sa.Integer(), nullable=True),
    sa.Column('volatility_buffer', sa.Float(), nullable=True),
    sa.Column('max_leverage', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_email'), 'strategy', ['email'], unique=True)
    op.create_index(op.f('ix_strategy_id'), 'strategy', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_strategy_id'), table_name='strategy')
    op.drop_index(op.f('ix_strategy_email'), table_name='strategy')
    op.drop_table('strategy')
    op.drop_index(op.f('ix_backtest_symbol'), table_name='backtest')
    op.drop_index(op.f('ix_backtest_id'), table_name='backtest')
    op.drop_index(op.f('ix_backtest_email'), table_name='backtest')
    op.drop_table('backtest')
    # ### end Alembic commands ###
