"""add sharpe

Revision ID: 539694caa741
Revises: 3b26b0303bda
Create Date: 2024-11-04 14:57:42.095241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '539694caa741'
down_revision: Union[str, None] = '3b26b0303bda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest', sa.Column('sharpe_ratio', sa.Integer(), nullable=True))
    op.add_column('backtest', sa.Column('max_drawdown', sa.Integer(), nullable=True))
    op.add_column('backtest', sa.Column('cagr', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backtest', 'cagr')
    op.drop_column('backtest', 'max_drawdown')
    op.drop_column('backtest', 'sharpe_ratio')
    # ### end Alembic commands ###
