"""add data_source BacktestResult

Revision ID: ace3c9707e02
Revises: ac53b722c31d
Create Date: 2024-11-24 14:53:47.933898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ace3c9707e02'
down_revision: Union[str, None] = 'ac53b722c31d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest', sa.Column('data_source', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backtest', 'data_source')
    # ### end Alembic commands ###
