"""merge with master

Revision ID: b11de688ca32
Revises: f23f211313de
Create Date: 2024-11-24 14:17:44.804544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'b11de688ca32'
down_revision: Union[str, None] = 'f23f211313de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_strategy_email', table_name='strategy')
    op.drop_index('ix_strategy_id', table_name='strategy')
    op.drop_table('strategy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('allocation', sa.INTEGER(), nullable=True),
    sa.Column('positionType', sa.VARCHAR(), nullable=True),
    sa.Column('entryRules', sqlite.JSON(), nullable=True),
    sa.Column('exitRules', sqlite.JSON(), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.Column('regime_filter', sa.VARCHAR(), nullable=True),
    sa.Column('position_size_method', sa.VARCHAR(), nullable=True),
    sa.Column('fixed_position_size', sa.FLOAT(), nullable=True),
    sa.Column('volatility_target', sa.FLOAT(), nullable=True),
    sa.Column('volatility_lookback', sa.INTEGER(), nullable=True),
    sa.Column('volatility_buffer', sa.FLOAT(), nullable=True),
    sa.Column('max_leverage', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_strategy_id', 'strategy', ['id'], unique=False)
    op.create_index('ix_strategy_email', 'strategy', ['email'], unique=1)
    # ### end Alembic commands ###
