"""Initial migration

Revision ID: f23f211313de
Revises: 902132791d4b
Create Date: 2024-11-17 13:23:30.119429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f23f211313de'
down_revision: Union[str, None] = '902132791d4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('start', sa.String(), nullable=True),
    sa.Column('end', sa.String(), nullable=True),
    sa.Column('fees', sa.Integer(), nullable=True),
    sa.Column('slippage', sa.Integer(), nullable=True),
    sa.Column('strategies', sa.JSON(), nullable=True),
    sa.Column('sharpe_ratio', sa.Integer(), nullable=True),
    sa.Column('max_drawdown', sa.Integer(), nullable=True),
    sa.Column('cagr', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_email'), 'backtest', ['email'], unique=False)
    op.create_index(op.f('ix_backtest_id'), 'backtest', ['id'], unique=False)
    op.create_index(op.f('ix_backtest_symbol'), 'backtest', ['symbol'], unique=False)
    op.create_table('price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('market', sa.String(), nullable=True),
    sa.Column('time', sa.Float(), nullable=True),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_id'), 'price', ['id'], unique=False)
    op.create_index(op.f('ix_price_market'), 'price', ['market'], unique=False)
    op.create_index(op.f('ix_price_symbol'), 'price', ['symbol'], unique=False)
    op.create_index(op.f('ix_price_time'), 'price', ['time'], unique=False)
    op.create_table('strategy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('allocation', sa.Integer(), nullable=True),
    sa.Column('positionType', sa.String(), nullable=True),
    sa.Column('entryRules', sa.JSON(), nullable=True),
    sa.Column('exitRules', sa.JSON(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('regime_filter', sa.String(), nullable=True),
    sa.Column('position_size_method', sa.String(), nullable=True),
    sa.Column('fixed_position_size', sa.Float(), nullable=True),
    sa.Column('volatility_target', sa.Float(), nullable=True),
    sa.Column('volatility_lookback', sa.Integer(), nullable=True),
    sa.Column('volatility_buffer', sa.Float(), nullable=True),
    sa.Column('max_leverage', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_email'), 'strategy', ['email'], unique=True)
    op.create_index(op.f('ix_strategy_id'), 'strategy', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strategy_id'), table_name='strategy')
    op.drop_index(op.f('ix_strategy_email'), table_name='strategy')
    op.drop_table('strategy')
    op.drop_index(op.f('ix_price_time'), table_name='price')
    op.drop_index(op.f('ix_price_symbol'), table_name='price')
    op.drop_index(op.f('ix_price_market'), table_name='price')
    op.drop_index(op.f('ix_price_id'), table_name='price')
    op.drop_table('price')
    op.drop_index(op.f('ix_backtest_symbol'), table_name='backtest')
    op.drop_index(op.f('ix_backtest_id'), table_name='backtest')
    op.drop_index(op.f('ix_backtest_email'), table_name='backtest')
    op.drop_table('backtest')
    # ### end Alembic commands ###
